### ISSUE TITLE
Iterating over search pages throws KeyError

### ISSUE THREAD

**Issue by tomasbedrich** [tomasbedrich/pycaching#1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.8-intel/egg/pycaching/geocaching.py", line 124, in search
  File "build/bdist.macosx-10.8-intel/egg/pycaching/geocaching.py", line 155, in _searchGetPage
KeyError: 11

**Comment by tomasbedrich** [comment]
Closed by changing search method (see 975d61192e68a17a3338112e961a6aab03f547c8).
