### ISSUE TITLE
Localization issue ?

### ISSUE THREAD

**Issue by AntoineTurmel** [tomasbedrich/pycaching#14]
```py
>>> cache = geocaching.load_cache("GC12345")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.2/dist-packages/pycaching/geocaching.py", line 21, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/pycaching/geocaching.py", line 320, in load_cache
    c.cache_type = cache_type
  File "/usr/local/lib/python3.2/dist-packages/pycaching/cache.py", line 231, in cache_type
    raise ValueError("Cache type '{}' is not possible.".format(cache_type))
pycaching.errors.ValueError: Cache type 'Cache Mystère' is not possible.
```

(my geocaching.com account is in French)

**Comment by kif** [comment]
so your solution is to set your profile name to English ... not the most elegant way. pycaching should handle this.
I tried to add the french names but it fails a bit later with date parsing also hard-coded to english.

**Comment by tomasbedrich** [comment]
Fixed and published.
