### ISSUE TITLE
Failing test with cache loader by GUID on Travis

### ISSUE THREAD

**Issue by FriedrichFroebel** [tomasbedrich/pycaching#147]
The quick load functionality for getting a cache from its GUID fails on Travis:

```
======================================================================
ERROR: test__try_getting_cache_from_guid (test.test_geocaching.TestMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/tomasbedrich/pycaching/test/test_geocaching.py", line 107, in test__try_getting_cache_from_guid
    cache_pm.load_quick()  # necessary to get name for PMonly cache
  File "/home/travis/build/tomasbedrich/pycaching/pycaching/cache.py", line 776, in load_quick
    expect="json")
  File "/home/travis/build/tomasbedrich/pycaching/pycaching/geocaching.py", line 70, in _request
    raise Error("Cannot load page: {}".format(url)) from e
pycaching.errors.Error: Cannot load page: http://tiles01.geocaching.com/map.details
-------------------- >> begin captured logging << --------------------
root: INFO: Logging in...
root: DEBUG: Checking for previous login.
urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): www.geocaching.com:443
urllib3.connectionpool: DEBUG: https://www.geocaching.com:443 "GET /account/signin HTTP/1.1" 200 22182
root: DEBUG: Assembling POST data.
root: DEBUG: Submiting login form.
urllib3.connectionpool: DEBUG: https://www.geocaching.com:443 "POST /account/signin HTTP/1.1" 200 22394
root: DEBUG: Checking the result.
root: DEBUG: Checking for already logged user.
root: INFO: Logging out.
root: INFO: Loading cache with GUID '15ad3a3d-92c1-4f7c-b273-60937bcc2072'
root: INFO: Loading cache with GUID '328927c1-aa8c-4e0d-bf59-31f1ce44d990'
urllib3.connectionpool: DEBUG: https://www.geocaching.com:443 "GET /seek/cdpf.aspx?guid=328927c1-aa8c-4e0d-bf59-31f1ce44d990 HTTP/1.1" 200 11318
urllib3.connectionpool: DEBUG: https://www.geocaching.com:443 "GET /seek/cache_details.aspx?guid=328927c1-aa8c-4e0d-bf59-31f1ce44d990 HTTP/1.1" 301 242
urllib3.connectionpool: DEBUG: https://www.geocaching.com:443 "GET /geocache/GC74HEV_nidda-jenseits-der-rennstrecke-reloaded?guid=328927c1-aa8c-4e0d-bf59-31f1ce44d990 HTTP/1.1" 200 43731
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): tiles01.geocaching.com:80
urllib3.connectionpool: DEBUG: http://tiles01.geocaching.com:80 "GET /map.details?i=GC74HEV HTTP/1.1" 302 0
urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): tiles01.geocaching.com:443
urllib3.connectionpool: DEBUG: https://tiles01.geocaching.com:443 "GET /map.details?i=GC74HEV HTTP/1.1" 503 326
--------------------- >> end captured logging << ---------------------
```

Strange enough, this seems to fail in one out of the three jobs only - and with a different job each time. I have not been able to reproduce this locally.

Example PRs where this fails: #145 and #146.

**Comment by tomasbedrich** [comment]
This is almost always resolved by restarting the job (which I sometimes do manually).

I suppose Groundspeak introduced some rate-limits, which we hit when running tests from CI. The [error code 503](https://httpstatuses.com/503) may be a cue.

Maybe we can introduce some ENV variable to artificially slow-down tests on CI. But I don't really know if this helps.

**Comment by FriedrichFroebel** [comment]
It seems like one can limit the number of concurrent docs as per [official blog](https://blog.travis-ci.com/2014-07-18-per-repository-concurrency-setting/). I have enabled the setting and limited it to 1 for now - let's see if this helps. (I will keep this issue open until we could verify this.)

**Comment by FriedrichFroebel** [comment]
Travis CI has been replaced by GitHub Actions, so this should be obsolete.
