### ISSUE TITLE
IndexError when loading geocache from a deleted owner

### ISSUE THREAD

**Issue by aa599** [tomasbedrich/pycaching#161]
The cache appears to be OK on [geocaching.com](https://www.geocaching.com/seek/geocache_logs.aspx?guid=1d3a1188-2c07-4d94-9077-1be8cedde405)

```
>>> import pycaching
>>> geocaching = pycaching.login()
>>> cache = geocaching.get_cache("GC1MX0C")
>>> logs = list(cache.load_logbook())

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycaching/util.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycaching/cache.py", line 640, in _logbook_token
    return self.__logbook_token
AttributeError: 'Cache' object has no attribute '_Cache__logbook_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycaching/cache.py", line 1028, in load_logbook
    logbook_page = self._logbook_get_page(page, per_page)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycaching/cache.py", line 1002, in _logbook_get_page
    "tkn": self._logbook_token,  # will trigger lazy_loading if needed
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycaching/util.py", line 31, in wrapper
    self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycaching/cache.py", line 723, in load
    self.author = cache_details("a")[1].text
IndexError: list index out of range

```

**Comment by FriedrichFroebel** [comment]
This is related to the geocache owner being a deleted user.

Using something like

```python
            try:
                self.author = cache_details("a")[1].text
            except IndexError:
                if "[DELETED_USER]" in cache_details.find("div", id="ctl00_ContentBody_mcd1").text:
                    self.author = "[DELETED_USER]"
                else:
                    self.author = None
```

works, but I am unsure on how we should actually handle this.

**Comment by tomasbedrich** [comment]
Good catch. I don't get the part with `self.author = "[DELETED_USER]"`. From my point of view simply setting `self.author = None` is totally fine in this case.

FWIW we need to handle all loading mechanisms.

**Comment by FriedrichFroebel** [comment]
My code was just some sort of quick fix, without having a look at the quick load functionality for example which might also need fixing. The `DELETED_USER` stuff might be removed as it does not have any real advantages, except that we would have different cases for known parsing problems vs. unknown parsing problems.

**Comment by tomasbedrich** [comment]
Sure, your code was helpful point to start the discussion. 👍🏻 Now I see – to distinguish DELETED_USER and other parsing problems, I would propose raising an exception instead. If I edit your snippet, it would be:
```
            try:
                self.author = cache_details("a")[1].text
            except IndexError:
                if "[DELETED_USER]" in cache_details.find("div", id="ctl00_ContentBody_mcd1").text:
                    self.author = None
                else:
                    raise
```
This way we could get faster feedback from users if something is wrong. What do you think?

**Comment by FriedrichFroebel** [comment]
I actually thought of the same approach for my approach initially, but have not been sure as I already mentioned. So I agree that your change is actually a bit cleaner and probably the way to go.
