### ISSUE TITLE
printing trackable information results in exceptions

### ISSUE THREAD

**Issue by mrummuka** [tomasbedrich/pycaching#87]
vagrant@vagrant:~$ ./env/bin/python 
Python 3.5.2 (default, Jul  5 2016, 12:43:10) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, datetime, pycaching, logging, time
>>> from pycaching.log import Log, Type as LogType
>>> logging.basicConfig(filename='tblog.log',level=logging.DEBUG)
>>> trcode='PLE556'
>>> geocaching = pycaching.login()
>>> trackable = geocaching.get_trackable(trcode)
>>> trackable
<pycaching.trackable.Trackable object at 0x7fc4497cc7b8>
>>> trackable.name
Traceback (most recent call last):
  File "/home/vagrant/env/lib/python3.5/site-packages/pycaching/util.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/vagrant/env/lib/python3.5/site-packages/pycaching/trackable.py", line 79, in name
    return self._name
AttributeError: 'Trackable' object has no attribute '_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/env/lib/python3.5/site-packages/pycaching/util.py", line 30, in wrapper
    self.load()
  File "/home/vagrant/env/lib/python3.5/site-packages/pycaching/trackable.py", line 199, in load
    if "cache_details" in location_url:
TypeError: argument of type 'NoneType' is not iterable

also:
>>> print(trackable.name, trackable.goal, trackable.description, trackable.location)
Traceback (most recent call last):
  File "/home/vagrant/env/lib/python3.5/site-packages/pycaching/util.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/home/vagrant/env/lib/python3.5/site-packages/pycaching/trackable.py", line 95, in location
    return self._location
AttributeError: 'Trackable' object has no attribute '_location'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/env/lib/python3.5/site-packages/pycaching/util.py", line 30, in wrapper
    self.load()
  File "/home/vagrant/env/lib/python3.5/site-packages/pycaching/trackable.py", line 199, in load
    if "cache_details" in location_url:
TypeError: argument of type 'NoneType' is not iterable

**Comment by mrummuka** [comment]
Ah. This is probably of my own fault of calling asynchronous functions but expecting synchronous results. Would you happen to have any code examples how trackable = geocaching.get_trackable(trcode) should be called in order to make sure it is completed before proceeding forward?

**Comment by tomasbedrich** [comment]
Hello @mrummuka, your code seems to be perfectly right. You have probably re-discovered the issue fixed with this commit: https://github.com/tomasbedrich/pycaching/commit/d4a491e7ef42a662a40e7aae9d95e437a4b698e6 Althrough this commit is pretty old, I somehow forgot to make a PyPI relase until recently –
 sorry for that. So please try it again with the latest release and let me know.

**Comment by jarhill0** [comment]
I'm not OP, but I tried this again with pycaching version 3.6.1 and it worked as expected.
